% ============================================================================
% BREAD COMPANY MODEL
% ============================================================================

% === OVERVIEW DOCUMENTATION ===
doc(title, 'Bread Company Operations').
doc(version, '0.1.0').
doc(author, 'Generated by LLM').
doc(overview, 'A bread company with production, logistics, retail, and customer demand.').
doc(description, 'Actors communicate via messages. Production and customer arrivals are probabilistic chance nodes. Pie/line charts should visualize message volume by sender.').

% === ROLE DOCUMENTATION ===
doc(role_factory, 'Factory mixes, kneads, bakes, cools, and bags bread.').
doc(role_bakers, 'Bakers operate machines, knead dough, and manage oven loads.').
doc(role_truck, 'Truck loads bagged bread and delivers to the storefront.').
doc(role_storefront, 'Storefront receives bread, stocks racks, sells to customers, and manages aging inventory.').
doc(role_customers, 'Customers arrive stochastically and buy bread from the fresh rack.').
doc(role_charity, 'Charity rack receives bread older than 3 days.').
doc(role_accounting, 'Accounting tracks wages, revenue, and profitability.').

% === VISUALIZATION GUIDE ===
doc(viz_statemachine, 'State machines show operational modes per actor. Chance states model probabilistic events.').
doc(viz_sequence, 'Sequence diagram shows a typical day: production -> delivery -> stocking -> customer sales -> accounting updates.').
doc(viz_pie, 'Pie chart shows message volume by sender (actor).').
doc(viz_line, 'Line chart shows cumulative messages by sender over sequence order.').

% === LINE CHART OPTIONS ===
line_chart_option(simulation, rate, 50).
line_series_source(revenue, label, record_sales).
line_series_source(wages, label, record_wages).
line_series(profit, sub, revenue, wages).
line_chart(simulation, 'Message Rates', [factory, bakers, truck, storefront, customers, charity, accounting]).
line_chart(simulation, 'Profit', [profit]).

% === ACTORS ===
actor(factory).
actor(bakers).
actor(truck).
actor(storefront).
actor(customers).
actor(charity).
actor(accounting).

% === ACTOR INITIAL STATES ===
actor_initial(factory, factory_idle).
actor_initial(bakers, bakers_idle).
actor_initial(truck, truck_idle).
actor_initial(storefront, store_closed).
actor_initial(customers, customers_idle).
actor_initial(charity, charity_idle).
actor_initial(accounting, accounting_break_even).

% === ACTOR STATES ===
actor_state(factory, factory_idle, [ready]).
actor_state(factory, factory_chance_batch, [chance]).
actor_state(factory, factory_mixing, [in_progress]).
actor_state(factory, factory_kneading, [in_progress]).
actor_state(factory, factory_baking, [in_progress]).
actor_state(factory, factory_cooling, [in_progress]).
actor_state(factory, factory_bagging, [bagged_stock]).
actor_state(factory, factory_waiting_truck, [bagged_stock]).

actor_state(bakers, bakers_idle, [available]).
actor_state(bakers, bakers_running_mixer, [busy]).
actor_state(bakers, bakers_kneading, [busy]).
actor_state(bakers, bakers_loading_oven, [busy]).
actor_state(bakers, bakers_unloading_oven, [busy]).

actor_state(truck, truck_idle, [available]).
actor_state(truck, truck_loading, [busy]).
actor_state(truck, truck_in_transit, [busy]).
actor_state(truck, truck_unloading, [busy]).

actor_state(storefront, store_closed, [closed]).
actor_state(storefront, store_open, [open]).
actor_state(storefront, store_stocking, [open]).
actor_state(storefront, store_fresh_rack_full, [fresh_stock]).
actor_state(storefront, store_fresh_rack_low, [fresh_stock, low_stock]).
actor_state(storefront, store_charity_rack, [has_charity_stock]).
actor_state(storefront, store_rotating_stock, [aging_stock]).
actor_state(storefront, store_sold_out, [no_stock]).

actor_state(customers, customers_idle, [chance]).
actor_state(customers, customers_arriving_low, [arriving]).
actor_state(customers, customers_arriving_high, [arriving]).
actor_state(customers, customers_buying, [buying]).

actor_state(charity, charity_idle, [ready]).
actor_state(charity, charity_receiving, [receiving]).
actor_state(charity, charity_stocked, [has_stock]).

actor_state(accounting, accounting_break_even, [neutral]).
actor_state(accounting, accounting_profitable, [profitable]).
actor_state(accounting, accounting_loss, [loss]).
actor_state(accounting, accounting_payroll, [wages_due]).
actor_state(accounting, accounting_revenue, [revenue_in]).

% === ACTOR TRANSITIONS ===
actor_transition(factory, factory_idle, start_day, factory_chance_batch).
actor_transition(factory, factory_chance_batch, batch_low, factory_mixing).
actor_transition(factory, factory_chance_batch, batch_high, factory_mixing).
actor_transition(factory, factory_mixing, mixed, factory_kneading).
actor_transition(factory, factory_kneading, kneaded, factory_baking).
actor_transition(factory, factory_baking, baked, factory_cooling).
actor_transition(factory, factory_cooling, cooled, factory_bagging).
actor_transition(factory, factory_bagging, bagged, factory_waiting_truck).
actor_transition(factory, factory_waiting_truck, loaded, factory_idle).

actor_transition(bakers, bakers_idle, run_mixer, bakers_running_mixer).
actor_transition(bakers, bakers_running_mixer, dough_ready, bakers_kneading).
actor_transition(bakers, bakers_kneading, dough_kneaded, bakers_loading_oven).
actor_transition(bakers, bakers_loading_oven, oven_loaded, bakers_unloading_oven).
actor_transition(bakers, bakers_unloading_oven, oven_unloaded, bakers_idle).

actor_transition(truck, truck_idle, arrive_factory, truck_loading).
actor_transition(truck, truck_loading, loaded_truck, truck_in_transit).
actor_transition(truck, truck_in_transit, arrive_store, truck_unloading).
actor_transition(truck, truck_unloading, unloaded_store, truck_idle).

actor_transition(storefront, store_closed, open_store, store_open).
actor_transition(storefront, store_open, receive_delivery, store_stocking).
actor_transition(storefront, store_stocking, racks_full, store_fresh_rack_full).
actor_transition(storefront, store_fresh_rack_full, sell_bread, store_fresh_rack_low).
actor_transition(storefront, store_fresh_rack_low, sell_out, store_sold_out).
actor_transition(storefront, store_fresh_rack_low, restock, store_fresh_rack_full).
actor_transition(storefront, store_fresh_rack_full, rotate_stock, store_rotating_stock).
actor_transition(storefront, store_rotating_stock, moved_to_charity, store_charity_rack).
actor_transition(storefront, store_charity_rack, charity_rack_set, store_open).
actor_transition(storefront, store_sold_out, close_store, store_closed).

actor_transition(customers, customers_idle, chance_arrival, customers_arriving_low).
actor_transition(customers, customers_idle, chance_arrival_peak, customers_arriving_high).
actor_transition(customers, customers_arriving_low, browse, customers_buying).
actor_transition(customers, customers_arriving_high, rush, customers_buying).
actor_transition(customers, customers_buying, checkout, customers_idle).

actor_transition(charity, charity_idle, notify_pickup, charity_receiving).
actor_transition(charity, charity_receiving, stocked, charity_stocked).
actor_transition(charity, charity_stocked, clear_rack, charity_idle).

actor_transition(accounting, accounting_break_even, record_wages, accounting_payroll).
actor_transition(accounting, accounting_payroll, wages_paid, accounting_loss).
actor_transition(accounting, accounting_loss, record_sales, accounting_revenue).
actor_transition(accounting, accounting_revenue, profit_high, accounting_profitable).
actor_transition(accounting, accounting_revenue, profit_low, accounting_break_even).
actor_transition(accounting, accounting_profitable, record_wages, accounting_payroll).

% === MESSAGE ANNOTATIONS (for sequence derivation if needed) ===
msg_annotation(start_day, send, bakers).
msg_annotation(mixed, send, bakers).
msg_annotation(kneaded, send, bakers).
msg_annotation(baked, send, bakers).
msg_annotation(cooled, send, bakers).
msg_annotation(bagged, send, truck).
msg_annotation(loaded_truck, send, truck).
msg_annotation(arrive_store, send, storefront).
msg_annotation(receive_delivery, recv, truck).
msg_annotation(sell_bread, recv, customers).
msg_annotation(checkout, send, accounting).
msg_annotation(moved_to_charity, send, charity).

% === CHANNELS AND MESSAGE FLOW (for sequence derivation) ===
channel(factory_bakers, 1).
channel(factory_truck, 1).
channel(truck_store, 1).
channel(store_customers, 1).
channel(store_accounting, 1).
channel(store_charity, 1).

send(factory_bakers, start_day, factory_idle, factory_chance_batch).
send(factory_bakers, mixed, bakers_running_mixer, bakers_kneading).
send(factory_bakers, kneaded, bakers_kneading, bakers_loading_oven).
send(factory_bakers, baked, bakers_loading_oven, bakers_unloading_oven).
send(factory_bakers, cooled, bakers_unloading_oven, bakers_idle).

send(factory_truck, bagged, factory_bagging, factory_waiting_truck).
send(factory_truck, loaded_truck, truck_loading, truck_in_transit).

send(truck_store, deliver_bread, truck_in_transit, truck_unloading).
send(truck_store, receive_delivery, store_stocking, store_fresh_rack_full).

send(store_customers, arrive, customers_idle, customers_arriving_low).
send(store_customers, offer_bread, store_fresh_rack_full, store_fresh_rack_low).
send(store_customers, purchase_8, customers_buying, customers_idle).

send(store_accounting, record_sale, store_fresh_rack_low, store_fresh_rack_low).

send(store_charity, move_old_stock, store_rotating_stock, store_charity_rack).

recv(factory_bakers, start_day, bakers_idle, bakers_running_mixer).
recv(factory_bakers, mixed, factory_mixing, factory_kneading).
recv(factory_bakers, kneaded, factory_kneading, factory_baking).
recv(factory_bakers, baked, factory_baking, factory_cooling).
recv(factory_bakers, cooled, factory_cooling, factory_bagging).

recv(factory_truck, bagged, truck_idle, truck_loading).
recv(factory_truck, loaded_truck, factory_waiting_truck, factory_idle).

recv(truck_store, deliver_bread, store_open, store_stocking).
recv(truck_store, receive_delivery, truck_unloading, truck_idle).

recv(store_customers, arrive, store_open, store_open).
recv(store_customers, offer_bread, customers_arriving_low, customers_buying).
recv(store_customers, purchase_8, store_fresh_rack_low, store_fresh_rack_low).

recv(store_accounting, record_sale, accounting_loss, accounting_revenue).

recv(store_charity, move_old_stock, charity_idle, charity_receiving).

% === DERIVED PREDICATES ===
prop(State, Prop) :- actor_state(_, State, Props), member(Prop, Props).
initial(S) :- actor_initial(_, S).
transition(From, Label, To) :- actor_transition(_, From, Label, To).

% === CTL PROPERTIES ===
property(profitable_eventually, 'Business can reach profitability', 'ag(ef(atom(profitable)))').
property(avoid_permanent_stockout, 'Fresh rack not permanently empty', 'ag(ef(atom(fresh_stock)))').
property(charity_receives_old_stock, 'Old stock eventually moved to charity', 'ag(ef(atom(has_charity_stock)))').
property(wages_recorded, 'Payroll is eventually recorded', 'ag(ef(atom(wages_due)))').
property(open_store_reachable, 'Store can open from initial conditions', 'ag(ef(atom(open)))').
