% ============================================================================
% KERBEROS PROTOCOL - SIMPLIFIED
% ============================================================================

% === OVERVIEW DOCUMENTATION ===
doc(title, 'Kerberos (Simplified)').
doc(version, '0.1.0').
doc(author, 'Generated by LLM').
doc(overview, 'Client obtains tickets from AS and TGS to access a service.').
doc(description, 'Sequence derived from send/recv on channels.').

% === ROLE DOCUMENTATION ===
doc(role_client, 'Client requests tickets and authenticates to the service.').
doc(role_as, 'Authentication Server issues a TGT.').
doc(role_tgs, 'Ticket Granting Server issues service tickets.').
doc(role_service, 'Service accepts the client ticket.').
doc(vars, 'TGT is the ticket-granting ticket; Kc_tgs is client-TGS session key; Kc_svc is client-service session key; Auth is an authenticator; SvcTicket is the service ticket.').
doc(role_attacker, 'Attacker can steal tickets or forge them after compromising TGS.').

% === ACTORS ===
actor(client).
actor(as).
actor(tgs).
actor(service).
actor(attacker).

% === ACTOR INITIAL STATES ===
actor_initial(client, c_idle).
actor_initial(as, as_idle).
actor_initial(tgs, tgs_idle).
actor_initial(service, s_idle).
actor_initial(attacker, attacker_idle).

% === ACTOR STATES ===
actor_state(client, c_idle, [ready]).
actor_state(client, c_sent_as_req, [waiting]).
actor_state(client, c_got_tgt, [has_tgt]).
actor_state(client, c_sent_tgs_req, [waiting]).
actor_state(client, c_got_svc_ticket, [has_ticket]).
actor_state(client, c_authenticated, [authed]).

actor_state(as, as_idle, [ready]).
actor_state(as, as_received, [processing]).
actor_state(as, as_responded, [responded]).

actor_state(tgs, tgs_idle, [ready]).
actor_state(tgs, tgs_received, [processing]).
actor_state(tgs, tgs_responded, [responded]).

actor_state(service, s_idle, [ready]).
actor_state(service, s_received, [processing]).
actor_state(service, s_accepted, [authed]).

actor_state(attacker, attacker_idle, [ready]).
actor_state(attacker, attacker_got_tgt, [attacker_has_tgt]).
actor_state(attacker, attacker_got_ticket, [attacker_has_ticket]).
actor_state(attacker, attacker_authed, [attacker_authed]).
actor_state(attacker, attacker_compromised, [attacker_can_forge]).

% === ACTOR TRANSITIONS ===
actor_transition(client, c_idle, send_as_req, c_sent_as_req).
actor_transition(client, c_sent_as_req, recv_as_rep, c_got_tgt).
actor_transition(client, c_got_tgt, send_tgs_req, c_sent_tgs_req).
actor_transition(client, c_sent_tgs_req, recv_tgs_rep, c_got_svc_ticket).
actor_transition(client, c_got_svc_ticket, send_ap_req, c_authenticated).

actor_transition(as, as_idle, recv_as_req, as_received).
actor_transition(as, as_received, send_as_rep, as_responded).
actor_transition(as, as_responded, reset, as_idle).

actor_transition(tgs, tgs_idle, recv_tgs_req, tgs_received).
actor_transition(tgs, tgs_received, send_tgs_rep, tgs_responded).
actor_transition(tgs, tgs_responded, reset, tgs_idle).

actor_transition(service, s_idle, recv_ap_req, s_received).
actor_transition(service, s_received, send_ap_rep, s_accepted).
actor_transition(service, s_accepted, reset, s_idle).

actor_transition(attacker, attacker_idle, steal_tgt, attacker_got_tgt).
actor_transition(attacker, attacker_got_tgt, use_tgt, attacker_got_ticket).
actor_transition(attacker, attacker_idle, steal_ticket, attacker_got_ticket).
actor_transition(attacker, attacker_got_ticket, use_ticket, attacker_authed).
actor_transition(attacker, attacker_idle, compromise_tgs, attacker_compromised).
actor_transition(attacker, attacker_compromised, forge_ticket, attacker_got_ticket).

% === CHANNELS AND MESSAGE FLOW (for sequence derivation) ===
channel(c_as, 1).
channel(as_c, 1).
channel(c_tgs, 1).
channel(tgs_c, 1).
channel(c_svc, 1).
channel(svc_c, 1).

message_format(as_req, 'C').
message_format(as_rep, 'TGT,Kc_tgs').
message_format(tgs_req, 'TGT,Auth').
message_format(tgs_rep, 'SvcTicket,Kc_svc').
message_format(ap_req, 'SvcTicket,Auth').
message_format(ap_rep, 'Ack').

send(c_as, as_req, c_idle, c_sent_as_req).
send(as_c, as_rep, as_received, as_responded).
send(c_tgs, tgs_req, c_got_tgt, c_sent_tgs_req).
send(tgs_c, tgs_rep, tgs_received, tgs_responded).
send(c_svc, ap_req, c_got_svc_ticket, c_authenticated).
send(svc_c, ap_rep, s_received, s_accepted).

recv(c_as, as_req, as_idle, as_received).
recv(as_c, as_rep, c_sent_as_req, c_got_tgt).
recv(c_tgs, tgs_req, tgs_idle, tgs_received).
recv(tgs_c, tgs_rep, c_sent_tgs_req, c_got_svc_ticket).
recv(c_svc, ap_req, s_idle, s_received).
recv(svc_c, ap_rep, c_authenticated, c_authenticated).

% === DERIVED PREDICATES ===
prop(State, Prop) :- actor_state(_, State, Props), member(Prop, Props).
initial(S) :- actor_initial(_, S).
transition(From, Label, To) :- actor_transition(_, From, Label, To).

% === CTL PROPERTIES ===
property(client_authenticates, 'Client can authenticate to service', 'ag(ef(atom(authed)))').
property(attacker_can_get_ticket, 'Attacker can obtain a service ticket', 'ef(atom(attacker_has_ticket))').
property(attacker_can_authenticate, 'Attacker can authenticate to service', 'ef(atom(attacker_authed))').
property(attacker_never_authenticates, 'Attacker never authenticates', 'ag(not(atom(attacker_authed)))').
