% ============================================================================
% NEEDHAM-SCHROEDER (SYMMETRIC KEY) PROTOCOL - SIMPLIFIED
% ============================================================================

% === OVERVIEW DOCUMENTATION ===
doc(title, 'Needham-Schroeder (Symmetric Key)').
doc(version, '0.1.0').
doc(author, 'Generated by LLM').
doc(overview, 'A and B use a trusted server S to establish a session key Kab.').
doc(description, 'Sequence derived from send/recv on channels.').

% === ROLE DOCUMENTATION ===
doc(role_initiator, 'A initiates by requesting a session key for B.').
doc(role_responder, 'B completes challenge-response with A.').
doc(role_server, 'S issues Kab and a ticket for B.').
doc(role_attacker, 'Attacker can steal tickets or forge them after compromising S.').

% === ACTORS ===
actor(a).
actor(b).
actor(s).
actor(attacker).

% === ACTOR INITIAL STATES ===
actor_initial(a, a_idle).
actor_initial(b, b_idle).
actor_initial(s, s_idle).
actor_initial(attacker, attacker_idle).

% === ACTOR STATES ===
actor_state(a, a_idle, [ready]).
actor_state(a, a_sent_req, [waiting]).
actor_state(a, a_got_ticket, [has_ticket]).
actor_state(a, a_sent_ticket, [waiting]).
actor_state(a, a_established, [kab_established]).

actor_state(b, b_idle, [ready]).
actor_state(b, b_got_ticket, [has_ticket]).
actor_state(b, b_sent_nb, [waiting]).
actor_state(b, b_established, [kab_established]).

actor_state(s, s_idle, [ready]).
actor_state(s, s_received, [processing]).
actor_state(s, s_responded, [responded]).

actor_state(attacker, attacker_idle, [ready]).
actor_state(attacker, attacker_got_ticket, [attacker_has_ticket]).
actor_state(attacker, attacker_got_kab, [attacker_has_kab]).
actor_state(attacker, attacker_compromised, [attacker_can_forge]).

% === ACTOR TRANSITIONS ===
actor_transition(a, a_idle, send_req, a_sent_req).
actor_transition(a, a_sent_req, recv_ticket, a_got_ticket).
actor_transition(a, a_got_ticket, send_ticket, a_sent_ticket).
actor_transition(a, a_sent_ticket, recv_nb, a_established).

actor_transition(b, b_idle, recv_ticket, b_got_ticket).
actor_transition(b, b_got_ticket, send_nb, b_sent_nb).
actor_transition(b, b_sent_nb, recv_nb_ack, b_established).

actor_transition(s, s_idle, recv_req, s_received).
actor_transition(s, s_received, send_ticket, s_responded).
actor_transition(s, s_responded, reset, s_idle).

actor_transition(attacker, attacker_idle, steal_ticket, attacker_got_ticket).
actor_transition(attacker, attacker_got_ticket, use_ticket, attacker_got_kab).
actor_transition(attacker, attacker_idle, compromise_s, attacker_compromised).
actor_transition(attacker, attacker_compromised, forge_ticket, attacker_got_ticket).

% === CHANNELS AND MESSAGE FLOW (for sequence derivation) ===
channel(a_s, 1).
channel(s_a, 1).
channel(a_b, 1).
channel(b_a, 1).

message_format(req_ab_na, 'A,B,Na').
message_format(ticket_kab, 'Kab,ticket_b').
message_format(nb, 'Nb').
message_format(nb_ack, 'Nb-1').

send(a_s, req_ab_na, a_idle, a_sent_req).
send(s_a, ticket_kab, s_received, s_responded).
send(a_b, ticket_kab, a_got_ticket, a_sent_ticket).
send(b_a, nb, b_got_ticket, b_sent_nb).
send(a_b, nb_ack, a_sent_ticket, a_established).

recv(a_s, req_ab_na, s_idle, s_received).
recv(s_a, ticket_kab, a_sent_req, a_got_ticket).
recv(a_b, ticket_kab, b_idle, b_got_ticket).
recv(b_a, nb, a_sent_ticket, a_established).
recv(a_b, nb_ack, b_sent_nb, b_established).

% === DERIVED PREDICATES ===
prop(State, Prop) :- actor_state(_, State, Props), member(Prop, Props).
initial(S) :- actor_initial(_, S).
transition(From, Label, To) :- actor_transition(_, From, Label, To).

% === CTL PROPERTIES ===
property(a_establishes_key, 'A can establish Kab', 'ag(ef(atom(kab_established)))').
property(b_establishes_key, 'B can establish Kab', 'ag(ef(atom(kab_established)))').
property(attacker_can_get_ticket, 'Attacker can obtain a ticket', 'ef(atom(attacker_has_ticket))').
property(attacker_can_get_kab, 'Attacker can obtain Kab', 'ef(atom(attacker_has_kab))').
property(attacker_never_gets_kab, 'Attacker never learns Kab', 'ag(not(atom(attacker_has_kab)))').
