% ============================================================================
% YAHALOM KEY EXCHANGE PROTOCOL (SIMPLIFIED)
% ============================================================================

% === OVERVIEW DOCUMENTATION ===
doc(title, 'Yahalom Protocol').
doc(version, '0.1.0').
doc(author, 'Generated by LLM').
doc(overview, 'Three-party key exchange protocol with a trusted server.').
doc(description, 'Actors A and B use server S to establish a shared session key Kab.').

% === ROLE DOCUMENTATION ===
doc(role_initiator, 'A initiates the run by sending a fresh nonce to B.').
doc(role_responder, 'B responds and relays A and fresh nonces to S.').
doc(role_server, 'S creates a session key and returns tickets for A and B.').
doc(vars, 'Na,Nb are nonces; Kab is a session key; ticket_b is a ticket encrypted for B (e.g., {Kab,A}_Kbs).').
doc(role_attacker, 'Attacker can steal tickets or forge them after compromising S.').

% === VISUALIZATION GUIDE ===
doc(viz_sequence, 'Sequence is derived from send/recv on channels.').
doc(viz_statemachine, 'Explicit actor states make the protocol easy to diagram.').

% === ACTORS ===
actor(a).
actor(b).
actor(s).
actor(attacker).

% === ACTOR INITIAL STATES ===
actor_initial(a, a_idle).
actor_initial(b, b_idle).
actor_initial(s, s_idle).
actor_initial(attacker, attacker_idle).

% === ACTOR STATES ===
actor_state(a, a_idle, [ready]).
actor_state(a, a_sent_na, [waiting]).
actor_state(a, a_got_ticket, [has_ticket]).
actor_state(a, a_established, [kab_established]).

actor_state(b, b_idle, [ready]).
actor_state(b, b_got_na, [waiting]).
actor_state(b, b_sent_to_s, [waiting]).
actor_state(b, b_established, [kab_established]).

actor_state(s, s_idle, [ready]).
actor_state(s, s_received, [processing]).
actor_state(s, s_responded, [responded]).

actor_state(attacker, attacker_idle, [ready]).
actor_state(attacker, attacker_got_ticket, [attacker_has_ticket]).
actor_state(attacker, attacker_got_kab, [attacker_has_kab]).
actor_state(attacker, attacker_compromised, [attacker_can_forge]).

% === ACTOR TRANSITIONS ===
actor_transition(a, a_idle, send_ab_na, a_sent_na).
actor_transition(a, a_sent_na, recv_s_to_a, a_got_ticket).
actor_transition(a, a_got_ticket, send_ticket_to_b, a_established).

actor_transition(b, b_idle, recv_ab_na, b_got_na).
actor_transition(b, b_got_na, send_to_s, b_sent_to_s).
actor_transition(b, b_sent_to_s, recv_a_ticket, b_established).

actor_transition(s, s_idle, recv_b_to_s, s_received).
actor_transition(s, s_received, send_s_to_a, s_responded).
actor_transition(s, s_responded, reset, s_idle).

actor_transition(attacker, attacker_idle, steal_ticket, attacker_got_ticket).
actor_transition(attacker, attacker_got_ticket, use_ticket, attacker_got_kab).
actor_transition(attacker, attacker_idle, compromise_s, attacker_compromised).
actor_transition(attacker, attacker_compromised, forge_ticket, attacker_got_ticket).

transition_guard(attacker_idle, steal_ticket, attacker_got_ticket, chance_steal).
transition_guard(attacker_idle, compromise_s, attacker_compromised, chance_compromise).

transition_prob(attacker_idle, steal_ticket, attacker_got_ticket, 0.7).
transition_prob(attacker_idle, compromise_s, attacker_compromised, 0.3).

chance_steal :- dice0(0.0, 0.7).
chance_compromise :- dice0(0.7, 1.0).

% === CHANNELS AND MESSAGE FLOW (for sequence derivation) ===
channel(a_b, 1).
channel(b_s, 1).
channel(s_a, 1).
channel(a_b_ticket, 1).

message_format(na, 'A,Na').
message_format(a_na_nb, 'A,Na,Nb').
message_format(kab_ticket, 'Kab,ticket_b,Nb').

send(a_b, na, a_idle, a_sent_na).
send(b_s, a_na_nb, b_got_na, b_sent_to_s).
send(s_a, kab_ticket, s_received, s_responded).
send(a_b_ticket, kab_ticket, a_got_ticket, a_established).

recv(a_b, na, b_idle, b_got_na).
recv(b_s, a_na_nb, s_idle, s_received).
recv(s_a, kab_ticket, a_sent_na, a_got_ticket).
recv(a_b_ticket, kab_ticket, b_sent_to_s, b_established).

% === DERIVED PREDICATES ===
prop(State, Prop) :- actor_state(_, State, Props), member(Prop, Props).
initial(S) :- actor_initial(_, S).
transition(From, Label, To) :- actor_transition(_, From, Label, To).

% === CTL PROPERTIES ===
property(a_establishes_key, 'A can establish Kab', 'ag(ef(atom(kab_established)))').
property(b_establishes_key, 'B can establish Kab', 'ag(ef(atom(kab_established)))').
property(attacker_can_get_ticket, 'Attacker can obtain a ticket', 'ef(atom(attacker_has_ticket))').
property(attacker_can_get_kab, 'Attacker can obtain Kab', 'ef(atom(attacker_has_kab))').
property(attacker_never_gets_kab, 'Attacker never learns Kab', 'ag(not(atom(attacker_has_kab)))').
